baseURL = "https://www.joshuaangell.com/"
languageCode = "en-us"
title = "Joshua Angell"
publishDir = "docs"
theme = "loveit"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    weight = 2
    identifier = "research"
    name = "Research"
    url = "/research/"
  [[menu.main]]
    weight = 3
    identifier = "about_me"
    name = "About Me"
    url = "/about_me/"
  [[menu.main]]
    weight = 4
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
