baseURL = "https://www.joshuaangell.com/"
languageCode = "en-us"
title = "Joshua Angell"
publishDir = "docs"
theme = "loveit"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    weight = 2
    identifier = "research"
    name = "Research"
    url = "/research/"
  [[menu.main]]
    weight = 3
    identifier = "about"
    name = "About Me"
    url = "/about/"
  [[menu.main]]
    weight = 4
    identifier = "photos"
    name = "Photos"
    url = "/photos/"

[params]
  defaultTheme = "auto"
  title = "Joshua Angell"

  # Home page config
  [params.home]
    [params.home.profile]
      enable = false
    [params.home.posts]
      enable = true
    [params.social]
      # Googlescholar = ""
      Phone = "(484) 843-0581"
      Email = "joshuanangell@gmail.com"

  [params.header]
    [params.header.title]
      name = "Joshua Angell"
